name: LPT
description: |
  Simple plugin to customise tablist and
  show players' prefixes
author: bernardMC
main: ar.com.caputo.lptags.LuckPermsTags
version: 1.2
api-version: 1.19
depend: [LuckPerms]